### ISSUE TITLE
[BUG] sandbox iodide notebook doesn't import packages

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide-examples#17]
I was trying to use the sandbox [notebook](https://iodide-project.github.io/master/) but was unable to import packages like d3.js using the same import block as the [eviction example](https://iodide-project.github.io/iodide-examples/eviction-notices-by-sf-neighborhood--1999-2015.html). I think that the sandbox version might be an older version that was not able to do this or there is something going awry there.

**Comment by bcolloran** [comment]
Hmmm well that's not good... just to double check here are the step I followed to attempt to replicate:

1. go to https://iodide-project.github.io/iodide-examples/eviction-notices-by-sf-neighborhood--1999-2015.html

2. from the third cell, copy the text
```https://cdnjs.cloudflare.com/ajax/libs/d3/4.10.2/d3.js
https://cdnjs.cloudflare.com/ajax/libs/metrics-graphics/2.13.0/metricsgraphics.min.js
https://cdnjs.cloudflare.com/ajax/libs/metrics-graphics/2.13.0/metricsgraphics.min.css``

3. open a blank notebook at https://iodide-project.github.io/master/

4. in command mode, press `e` to change the first cell to an external resource cell

5. paste in the text copied in step (2)

6. `ctrl+enter` to evaluate the cell

this worked ok for me. can you try those steps and let me know if you are hitting an error? If so, any output from the webconsole would be very helpful, as would the exported notebook.

Thanks so much for letting us know that you ran into an issue Teon!

**Comment by teonbrooks** [comment]
oh, I didn't change the cell to an external resource cell. it works fine if I do the `e` context change. 

I just hit `shift+enter` to execute the cell. that seems to work in the eviction example without change the execution context but it doesn't in the empty notebook
