### ISSUE TITLE
Bubble sort has an early exit flag

### ISSUE THREAD

**Issue by dsblank** [iodide-project/iodide-examples#23]
Cool project, but your bubble sort example in your demo code isn't bubble sort. Bubble sort exits early if no swaps are made on a pass.  https://en.wikipedia.org/wiki/Bubble_sort

**Comment by hamilton** [comment]
Thanks for the issue @dsblank. @imshubhamsingh I believe you authored this notebook, correct?

**Comment by dsblank** [comment]
I think most of us teach bubble sort in only one version. As wikipedia says "The only significant advantage that bubble sort has over most other algorithms, even quicksort, but not insertion sort, is that the ability to detect that the list is sorted efficiently is built into the algorithm. When the list is already sorted (best-case), the complexity of bubble sort is only O(n)." 

Thanks for fixing!

**Comment by dsblank** [comment]
Looks like this is complete (although the idea of comparing algorithms in this manner is addressed in another issue).
